POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "add@gmail.com",
    "password": "test"
}
### Get all drivers
GET http://localhost:5000/api/drivers/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NTk4LCJleHAiOjE3Mzk1NDYzOTh9.G8dwHCTfHYBRmNdnzknd8WBVcuNEriVRLUIQvWwdoKo


### Get a single driver by ID
GET http://localhost:5000/api/drivers/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NTk4LCJleHAiOjE3Mzk1NDYzOTh9.G8dwHCTfHYBRmNdnzknd8WBVcuNEriVRLUIQvWwdoKo


### Register a new driver
POST http://localhost:5000/api/drivers/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NTk4LCJleHAiOjE3Mzk1NDYzOTh9.G8dwHCTfHYBRmNdnzknd8WBVcuNEriVRLUIQvWwdoKo

{
  "name": "Jane Smith",
  "licenseNumber": "DL654321",
  "vehicleId": 2
}


### Update driver details
PUT http://localhost:5000/api/drivers/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NTk4LCJleHAiOjE3Mzk1NDYzOTh9.G8dwHCTfHYBRmNdnzknd8WBVcuNEriVRLUIQvWwdoKo

{
  "name": "Patrick mugisha",
  "licenseNumber": "DL12364248",
  "vehicleId": 2
}


### Delete a driver
DELETE http://localhost:5000/api/drivers/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NTk4LCJleHAiOjE3Mzk1NDYzOTh9.G8dwHCTfHYBRmNdnzknd8WBVcuNEriVRLUIQvWwdoKo
