### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "DefaultPass123@"
}
### Get all fuel prices
GET http://localhost:5000/api/fuel-prices/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMjU5NywiZXhwIjoxNzM5NjM0Mzk3fQ.GH9e2Os-2BQJfzyRCY7bkFHRs6IkUE15a-D7ua1iIs0


### Get fuel prices for a specific station
GET http://localhost:5000/api/fuel-prices/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMjU5NywiZXhwIjoxNzM5NjM0Mzk3fQ.GH9e2Os-2BQJfzyRCY7bkFHRs6IkUE15a-D7ua1iIs0


### Set fuel price for a station
POST http://localhost:5000/api/fuel-prices/setPrice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YXRpb25fd29ya2VyIiwiaWF0IjoxNzM5Njg1OTM3LCJleHAiOjE3Mzk2ODc3Mzd9.FLbQy1vmlLgvU0nu8HsB4T6PiTbAXLyyCkv1vg4fkHg

{
  "stationId": 1,
  "fuelType": "petrol",
  "price": 1500
}


### Update fuel price
PUT http://localhost:5000/api/fuel-prices/update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMjU5NywiZXhwIjoxNzM5NjM0Mzk3fQ.GH9e2Os-2BQJfzyRCY7bkFHRs6IkUE15a-D7ua1iIs0

{
  "fuelType": "Diesel",
  "price": 2000
}


### Delete fuel price
DELETE http://localhost:5000/api/fuel-prices/delete/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMjU5NywiZXhwIjoxNzM5NjM0Mzk3fQ.GH9e2Os-2BQJfzyRCY7bkFHRs6IkUE15a-D7ua1iIs0

### Get fuel price by stationId
GET http://localhost:5000/api/fuel-prices/station/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5Nzg4NDE1LCJleHAiOjE3Mzk3OTAyMTV9.CBiEshozUlcdvzpGuiL2ge8a0crM2m7uL0kGED4ypp0
