POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "data1",
    "email": "data1@gmail.com",
    "password": "test",
    "role": "Admin"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}


###
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NDQxMDcxLCJleHAiOjE3NDAwNDU4NzF9.8kG7WiMMXBpx_eR0KwZdnVywx_i_lrcmKFI2BwBRRYo