POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "data2",
    "email": "data2@gmail.com",
    "password": "test",
    "role": "Worker"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "data2@gmail.com",
    "password": "test"
}


###
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6IldvcmtlciIsImlhdCI6MTczOTQ2MzA5NCwiZXhwIjoxNzM5NDYzMTI0fQ.5pQhO2HQj53hgkVcuwggSjU3AX66oeAgpcTmQhcBPMI
###
POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzM5NDYzMzQ0LCJleHAiOjE3Mzk0NjM5NDR9.h14henVDeFZxtigQqtG3np6OVY9ghHn0zwRh-4XWig4"
}
###
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzM5NDYzMzQ0LCJleHAiOjE3Mzk0NjM5NDR9.h14henVDeFZxtigQqtG3np6OVY9ghHn0zwRh-4XWig4"
}