### Register a new user
POST http://localhost:5000/api/stations/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0MDU1LCJleHAiOjE3Mzk1NDU4NTV9.bU4iXvODX87FxxMhn2wam4reIp9JrO6SWWZRIkqG3Z0
Content-Type: application/json

{
  "name": "merez Gas Station",
  "location": "Kigali, Rwanda",
  "userId": 4
}


### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "add@gmail.com",
    "password": "test"
}

### Get all users
GET http://localhost:5000/api/stations/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0MDU1LCJleHAiOjE3Mzk1NDU4NTV9.bU4iXvODX87FxxMhn2wam4reIp9JrO6SWWZRIkqG3Z0

### Get user by ID
GET http://localhost:5000/api/stations/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0MDU1LCJleHAiOjE3Mzk1NDU4NTV9.bU4iXvODX87FxxMhn2wam4reIp9JrO6SWWZRIkqG3Z0

### Update Station details
PUT http://localhost:5000/api/stations/update/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTQ0NDk5LCJleHAiOjE3Mzk1NDYyOTl9.KHnibmhH2ieA5GCJpBq9hXDkU9bvzvcJr5c7mx6W12g

{
    "name": "updatedStation",
    "location": "muhanga, Rwanda",
    "userId": 4
}


### Delete Station
DELETE http://localhost:5000/api/stations/delete/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTEzMDk1LCJleHAiOjE3Mzk1MTQ4OTV9._3FDKOLgPPfriF67CTOLxhoBHY9iia9IZkvvL7bgdpc
