### Register a new user
POST http://localhost:5000/api/stations/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YXRpb25fd29ya2VyIiwiaWF0IjoxNzM5NjgzNjcwLCJleHAiOjE3Mzk2ODU0NzB9.Asm7FHWeNhwzO6F4Xqdm8UnT7-h5tmds_GWzdWKojRU
Content-Type: application/json

{
  "name": "merez Gas Station",
  "location": "Kigali, Rwanda"
}


### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "Password1@"
}

### Get all users
GET http://localhost:5000/api/stations/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5ODg3MjI3LCJleHAiOjE3Mzk4ODkwMjd9.s66BHKS_QFKgQoYUUEmHMWgrv9L16N90rSlo5tHsyVk

### Get user by ID
GET http://localhost:5000/api/stations/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM5OTk5OTA2LCJleHAiOjE3NDAwMDE3MDZ9.hDYwBFyzZInU7Cf8DYKIrO29Va2OASoFttZvh5XQFgQ

### Update Station details
PUT http://localhost:5000/api/stations/update/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMTY2NSwiZXhwIjoxNzM5NjMzNDY1fQ.JkZcXvZ8rus7NJyWXV26SpavBIhMvyxtiY0vuHKQoE4

{
    "name": "updatedStation1",
    "location": "muhanga, Rwanda"
}


### Delete Station
DELETE http://localhost:5000/api/stations/delete/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczOTYzMTY2NSwiZXhwIjoxNzM5NjMzNDY1fQ.JkZcXvZ8rus7NJyWXV26SpavBIhMvyxtiY0vuHKQoE4