### Register a new user
POST http://localhost:5000/api/stations/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NDc0MjQ0LCJleHAiOjE3Mzk0NzYwNDR9.mBnQhRSVkGVea_nt_NmyKkTAOhVYLeglWpZfwX2gqfM
Content-Type: application/json

{
  "name": "merez Gas Station",
  "location": "Kigali, Rwanda",
  "userId": 3
}


### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "data1@gmail.com",
    "password": "test"
}

### Get all users
GET http://localhost:5000/api/stations/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTEyMzAzLCJleHAiOjE3Mzk1MTQxMDN9.UKPw10Ipin6VoM1q1wPmaPPdf3wTay2WMmWHftobJyA

### Get user by ID
GET http://localhost:5000/api/stations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTEzMDk1LCJleHAiOjE3Mzk1MTQ4OTV9._3FDKOLgPPfriF67CTOLxhoBHY9iia9IZkvvL7bgdpc

### Update Station details
PUT http://localhost:5000/api/stations/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTEzMDk1LCJleHAiOjE3Mzk1MTQ4OTV9._3FDKOLgPPfriF67CTOLxhoBHY9iia9IZkvvL7bgdpc

{
    "name": "updatedStation",
    "location": "muhanga, Rwanda",
    "userId": 6
}


### Delete Station
DELETE http://localhost:5000/api/stations/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NTEzMDk1LCJleHAiOjE3Mzk1MTQ4OTV9._3FDKOLgPPfriF67CTOLxhoBHY9iia9IZkvvL7bgdpc
