### Register a new user
POST http://localhost:5000/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NjA1MDQ2LCJleHAiOjE3Mzk2MDY4NDZ9.oBU2PUxPK_CQBn_k-jbgvMe1WoiKpoQ2-OCAHeEC4S4
Content-Type: application/json

{
    "name": "fabrice50",
    "email": "fabrice50@gmail.com",
    "password": "Fabrice@1",
    "role": "viewer"
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "fabrice50@gmail.com",
    "password": "NewPass456@"
}

### Get all users
GET http://localhost:5000/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YXRpb25fd29ya2VyIiwiaWF0IjoxNzM5NjU5NTQ3LCJleHAiOjE3Mzk2NjEzNDd9.Q7mhIsl6baLRv3lBiGkX7Hb-KV9QrrQJlH0zD9h9BXc

### Get user by ID
GET http://localhost:5000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InN0YXRpb25fd29ya2VyIiwiaWF0IjoxNzM5NjU5NTQ3LCJleHAiOjE3Mzk2NjEzNDd9.Q7mhIsl6baLRv3lBiGkX7Hb-KV9QrrQJlH0zD9h9BXc

### Update user details
PUT http://localhost:5000/api/users/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NjA3NjQwLCJleHAiOjE3Mzk2MDk0NDB9.Lg0tceAI6Kn_yVXwsOp4PdCgAEIrpJmdwZrxBwg74eg

{
    "name": "viewer",
    "email": "viewer@gmail.com",
    "role": "viewer"
}

### Delete user
DELETE http://localhost:5000/api/users/delete/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzM5NjA3NjQwLCJleHAiOjE3Mzk2MDk0NDB9.Lg0tceAI6Kn_yVXwsOp4PdCgAEIrpJmdwZrxBwg74eg
### logout user
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzM5NjA5OTQ1LCJleHAiOjE3Mzk2MTA1NDV9._PaAqjLQjpCp4wwVZehiPdr5r32DoR5HeQpiUcDvNEQ"
}

###
POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzM5NjEwMTYzLCJleHAiOjE3Mzk2MTA3NjN9.uBbppY9z5aC65xkIO3H7QSxQjpxrUsi3mC1L_jCuGV4"
}

### Change User Password
PUT http://localhost:5000/api/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbGUiOiJ2aWV3ZXIiLCJpYXQiOjE3Mzk4ODcwMjEsImV4cCI6MTczOTg4ODgyMX0.6i8bl28TUBvfPNRhVFvfirffMqOWqq43wIt7Y4MU8Oo

{
  "oldPassword": "NewPass456@",
  "newPassword": "NewPass456@"
}
